name: Terraform Production Apply

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-prod-apply:
    runs-on: [self-hosted, linux, x64]

    environment:
      name: production

    env:
      TF_ENV: prod
      TFVARS_FILE: envs/prod.tfvars
      BACKEND_CONFIG: backend-prod.hcl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check tools
        run: |
          terraform version
          aws sts get-caller-identity

      - name: Terraform init
        run: terraform init -backend-config=$BACKEND_CONFIG

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan production
        run: terraform plan -var-file=$TFVARS_FILE -out=tfplan

      - name: Show production plan
        run: terraform show -no-color tfplan

      - name: Terraform apply approved plan
        run: terraform apply -auto-approve tfplan

